[build-system]
requires = ["setuptools>=70.1", "setuptools_scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "craceplot"
dynamic = ["version"]

description = "craceplot: Visualisation of Data from crace"
authors = [
  { name = "Yunshuang Xiao" }
]
maintainers = [
  { name = "crace developers", email = "race.autoconfig@gmail.com" },
  { name = "Yunshuang Xiao", email = "yunshuang.xiao@ulb.be" }
]
readme = { file = "README.md", content-type = "text/markdown" }

license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
requires-python = ">=3.8"
classifiers = [
  "Intended Audience :: Developers",
  "Intended Audience :: Education", 
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Software Development :: Libraries :: Python Modules",

  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",

  "Operating System :: OS Independent",
]

dependencies = [
  "crace>=0.1.0",
  "matplotlib>=3.3.4",
  "numpy>=1.19.5",
  "pandas>=1.0.5",
  "plotly>=5.0.0",
  "scikit-learn>=0.24.2",
  "scikit_posthocs>=0.6.7",
  "scipy>=1.5.4",
  "seaborn>=0.11.0",
  "statannotations>=0.5.0",
  "statsmodels>=0.12.2"
]

[project.urls]
Homepage = "https://race-autoconfig.github.io/craceplot/"
Source = "https://github.com/race-autoconfig/craceplot/"
Tracker = "https://github.com/race-autoconfig/craceplot/issues"

[project.scripts]
craceplot = "craceplot.scripts:start_cplot"

[tool.setuptools]
packages = { find = {} }
include-package-data = true

[tool.setuptools.package-data]
craceplot = [
  "core/*",
  "plot/*",
  "inst/*",
]

[tool.setuptools_scm]
version_scheme = "post-release"
write_to = "craceplot/_version.py"
fallback_version = "0.1.0"
