# cplot/_description.py

from datetime import datetime

def _get_version():
    """
    read version information from
        1. _version.py generated by setuptools_scm
        2. _vergit.py formated using git archive
           * must set .gitattributes (crace/_vergit.py export-subst) in advanve
        3. .git/HEAD and .git/<ref> if src includes .git directory
        4. check the latest modification date of all src files
        0. fallback to _VERSION 
    """
    import os
    import inspect
    from pathlib import Path

    try:
        current_dir = Path(__file__).resolve().parent.parent
    except NameError:
        caller_file = inspect.stack()[1].filename
        current_dir = Path(caller_file).resolve().parent.parent

    dest_ver = current_dir / "_version.py"
    dest_git = current_dir / "_vergit.py"
    dest_git_dir = current_dir.parent / ".git"


    try:
        if os.path.exists(dest_ver):
            d = {}
            with open(dest_ver) as f:
                exec(f.read(), d)
            return d.get("version", d.get("__version__", _VERSION))
    except Exception:
        pass

    try:
        import re
        if os.path.exists(dest_git):
            d = {}
            with open(dest_git) as f:
                exec(f.read(), d)
            ver = d.get("version", d.get("__version__", _VERSION))
            match = re.search(r"tag:\s*([^,\)]+)", ver)
            if match: return match.group(1)
    except Exception:
        pass

    try:
        commit = None
        if os.path.exists(dest_git_dir):
            head = (dest_git_dir / "HEAD").read_text().strip()
            packed_tag = dest_git_dir / "packed-refs"

            if head.startswith("ref:"): 
                ref = head.split(" ", 1)[1]
                try:
                    commit = (dest_git_dir / ref).read_text().strip()[:7]
                except Exception:
                    for t in packed_tag.read_text().splitlines():
                        if t.startswith("#"): continue
                        s, r = t.split(" ", 1)
                        if r.strip() == ref:
                            commit = s[:7]
            else:
                commit = head[:7]

            if commit: return commit

    except Exception:
        pass

    ignore_files = {".git",
                    "__pycache__",
                    "build",
                    "dist",
    }
    try:
        latest = 0
        for root, dirs, files in os.walk(current_dir.parent):
            dirs[:] = [ d for d in dirs if d not in ignore_files]
            for f in files:
                p = Path(root) / f
                latest = max(latest, os.path.getmtime(p))
        return _VERSION + ' ' + datetime.fromtimestamp(latest).strftime("%b.%d.%Y")
    except Exception:
        pass

    return _VERSION


package_name = "cplot"
authors = ['Yunshuang Xiao']
maintainers = ['Yunshuang Xiao']
maintainers_email = ['yunshuang.xiao@ulb.be']
contact = 'crace developers'
contact_email = 'race.autoconfig@gmail.com'

description = "cplot: Visualisation of Data from crace"
long_description = """
cplot: Visualisation of Data from crace
==========================================================================

cplot provides a set of functions to create plots to visualize the data from the crace package.

The configuration process performed by crace will show at the end of the execution one or more configurations that are the best performing configurations found. This package provides a set of functions that allow to further assess the performance of these configurations and provides support to obtain insights about the details of the configuration process.
"""

url = "https://race-autoconfig.github.io/cplot/"
url_home = url
url_source = "https://github.com/race-autoconfig/cplot/"
url_tracker = "https://github.com/race-autoconfig/cplot/issues"
urls = {
    'Homepage': url_home,
    'Source': url_source,
    'Tracker': url_tracker,
}

_year = datetime.now().year
copyright = (
    f"Copyright (c) 2026-{_year} crace developers"
    if _year > 2026
    else "Copyright (c) 2026 crace developers"
)

license = f"""
This is free software: you can redistribute it and/or modify it under the terms of the MIT License as published by the Free Software Foundation.

This is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the MIT License for more details.

cplot builds as an additional tool for the crace package:
  crace: Continuous Racing for Automatic Algorithm Configuration
  {copyright}
"""

citiation = """
To cite package 'cplot' in publications, an appropriate citation is

  Yunshuang Xiao, Leslie Pérez Cáceres, Manuel López-Ibáñez, and Thomas Stützle. 2023. Algorithm Configuration via Continuously Racing: Preliminary Results. In Proceedings of the Companion Conference on Genetic and Evolutionary Computation (GECCO '23 Companion). Association for Computing Machinery, New York, NY, USA, 1744-1752. https://doi.org/10.1145/3583133.3596408

A BibTeX entry for LaTeX users is

@inproceedings{10.1145/3583133.3596408,
  title = {Algorithm Configuration via Continuously Racing: Preliminary Results},
  author = {Xiao, Yunshuang and Pérez Cáceres, Leslie and López-Ibáñez, Manuel and Stützle, Thomas},
  booktitle = {Proceedings of the Companion Conference on Genetic and Evolutionary Computation},
  pages = {1744-1752},
  year = {2023},
}
"""

_VERSION = "0.1.0"
update_logs = """

The first release of cplot, version 0.1.0.

"""


def __getattr__(name: str):
    if name == "version":
        ver = _get_version()
        globals()["version"] = ver
        return ver
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")